### ISSUE TITLE
PROGRAMMING TIP: what is github & source control?

### ISSUE THREAD

**Issue by geminiimatt** [NayanFlo0/BerlinNow#12]
A good way to learn this is to do "github for poets" . I recommend doing this before jumping into coding the app.
Here is the video playlist:
https://www.youtube.com/playlist?list=PLRqwX-V7Uu6ZF9C0YMKuns9sLDzK6zoiV

**Comment by NayanFlo0** [comment]
Hey Matt,

I haven't understood the command "cd" yet, even after him explaining. Could you explain it to me.

**Comment by NayanFlo0** [comment]
Hey everyone, I finished the playlist and understood everything after watching the individual videos once or twice but I haven't understood the last two. Can you help Matt?

10)   https://www.youtube.com/watch?v=lR_hYwCAaH4&list=PLRqwX- 
        V7Uu6ZF9C0YMKuns9sLDzK6zoiV&index=11&t=0s

11)   https://www.youtube.com/watch?v=8HPYsDTk17A&list=PLRqwX- 
        V7Uu6ZF9C0YMKuns9sLDzK6zoiV&index=12&t=0s

**Comment by NayanFlo0** [comment]
Hey everyone I finished the git and github for poets playlist and I feel like I understand  it.
